商品情報編集機能
matsuikohei/furima-38001 pull request #18
Opened 2022-05-13 12:41 UTC by matsuikohei

# What
商品情報編集画面の作成

# Why
商品情報編集機能の実装のため

ログイン状態の出品者は、商品情報編集ページに遷移できる動画
https://gyazo.com/17e8f3ea5c5b60932ea93dbd7d252022

必要な情報を適切に入力して「更新する」ボタンを押すと、商品の情報を編集できる動画
https://gyazo.com/eca0988ebbdbb84c1ff86d9d650d6e00

入力に問題がある状態で「変更する」ボタンが押された場合、情報は保存されず、編集ページに戻りエラーメッセージが表示される動画
https://gyazo.com/52f6e3ebb5bce53e142f2708f968c689

何も編集せずに「更新する」ボタンを押しても、画像無しの商品にならない動画
https://gyazo.com/5b6668edf289ac4d4a7594b48df51e96

ログイン状態の場合でも、URLを直接入力して自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移する動画
https://gyazo.com/35763deb1c0feb22149c3142d518a8dd

 ログアウト状態の場合は、URLを直接入力して商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずログインページに遷移する動画
https://gyazo.com/4ba55692760e4b05b27cda053b5fdde9

商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示される動画（商品画像・販売手数料・販売利益に関しては、表示されない状態で良い）
https://gyazo.com/dc736554928429ebbc86686d3383489e

2022-05-13 12:52 UTC, CHURO-MAU reviewed
レビュー依頼ありがとうございます！
キャプチャ動画確認いたしました！

コメントいたしましたので、ご確認お願いいたします。
修正後は、再度レビュー依頼フォームのご提出をお願いいたします。

2022-05-13 12:52 UTC, CHURO-MAU commented on app/controllers/items_controller.rb
> +    @item = Item.find(params[:id])
２７行目
こちらの記述は他のアクションでも、同様のものがございます。
private以下に新しくメソッドを作成し、before_actionで呼び出すようにしてみましょう。

2022-05-14 05:00 UTC, TakashiKozuma requested changes
レビュー依頼ありがとうございます！
修正点確認致しました。
コメントを追記いたしました。
ご確認お願いいたします。

修正後はコミット・プッシュのし忘れがないかご確認の上、再度フォームからレビュー依頼をお願い致します。

2022-05-14 05:00 UTC, TakashiKozuma commented on app/controllers/items_controller.rb
>      @item = Item.find(params[:id])
```rb
@item = Item.find(params[:id])
```
こちらの記述も`set_item`に記述されているのでupdateアクションにも`set_item`を適用し、こちらの記述は省略しましょう！

2022-05-14 05:41 UTC, TakashiKozuma commented
追加のレビュー依頼ありがとうございます！
修正点も含め、確認が完了しました。
LGTMです！！

こちらのブランチは忘れずにMergeいただき、ローカルのMasterにPullした後に次の実装のためのブランチを切ってから次にお進み下さい。

2022-05-14 05:45 UTC, merged